---
- name: See if Nexus is already deployed
  oc_obj:
    namespace: "{{ project_name }}"
    kind: "pod"
    selector: "deploymentconfig=nexus"
    state: list
    kubeconfig: "{{ lookup('env','HOME')}}/.kube/config"
  register: nexus_deployed
  tags:
    - deploy
    - undeploy

- set_fact:
    nexus_is_deployed: "'results' in nexus_deployed.results and nexus_deployed.results.results[0]['items'] | count > 0"
  tags:
    - deploy
    - undeploy

# Remove and Undeploy Nexus
- name: Remove Nexus template
  oc_obj:
    namespace: "{{ project_name }}"
    kind: template
    name: "nexus2-persistent"
    state: absent
    kubeconfig: "{{ lookup('env','HOME')}}/.kube/config"
  when: nexus_is_deployed
  tags:
    - undeploy

- name: Terminate Nexus application
  oc_scale:
    namespace: "{{ project_name }}"
    kind: dc
    name: "nexus"
    kubeconfig: "{{ lookup('env','HOME')}}/.kube/config"
  when: nexus_is_deployed
  tags:
    - undeploy

- name: Wait for Nexus undeployment
  oc_obj:
    namespace: "{{ project_name }}"
    kind: "pod"
    selector: "deploymentconfig=nexus"
    state: list
    kubeconfig: "{{ lookup('env','HOME')}}/.kube/config"
  register: nexus_undeploy
  until:
  - "'results' in nexus_undeploy.results and nexus_undeploy.results.results[0]['items'] | count == 0"
  delay: 5
  retries: 5
  when: nexus_is_deployed
  tags:
    - undeploy

- name: Remove Nexus deployment
  oc_obj:
    namespace: "{{ project_name }}"
    kind: "is,dc,rc,route,svc,pvc"
    selector: "app=nexus"
    state: absent
    kubeconfig: "{{ lookup('env','HOME')}}/.kube/config"
  when: nexus_is_deployed
  tags:
    - undeploy

- set_fact:
    nexus_is_deployed: false
  tags:
    - undeploy

# Begin deployment of Nexus
- name: Get Nexus template
  get_url:
    url: "https://raw.githubusercontent.com/OpenShiftDemos/nexus/master/nexus2-persistent-template.yaml"
    dest: "/tmp/nexus2-persistent-template.yaml"
    mode: 0400
  when: not nexus_is_deployed
  tags:
    - deploy

- name: Load Nexus template
  oc_obj:
    namespace: "{{ project_name }}"
    kind: template
    name: "nexus2-persistent"
    state: present
    kubeconfig: "{{ lookup('env','HOME')}}/.kube/config"
    files:
    - "/tmp/nexus2-persistent-template.yaml"
  when: not nexus_is_deployed
  tags:
    - deploy

- name: Deploy Nexus
  oc_process:
    namespace: "{{ project_name }}"
    template_name: "nexus2-persistent"
    create: true
    kubeconfig: "{{ lookup('env','HOME')}}/.kube/config"
  when: not nexus_is_deployed
  tags:
    - deploy

# Wait for the endpoint address of the nexus service to become active
- name: Verify Nexus deployment
  oc_obj:
    namespace: "{{ project_name }}"
    kind: ep
    name: "nexus"
    state: list
    kubeconfig: "{{ lookup('env','HOME')}}/.kube/config"
  when: not nexus_is_deployed
  register: nexus_deploy
  until:
  - "'results' in nexus_deploy.results and nexus_deploy.results['results'] | count > 0"
  - "{{nexus_deploy.results.results[0] | json_query(jp_query) | count > 0}}"
  delay: 20
  retries: 6
  vars:
    jp_query: "subsets[*].addresses"
  tags:
    - deploy
