---
# Build a component of the coolstore application
- name: Build {{ bc_name }}
  shell: "oc start-build {{ bc_name }} -n {{ project_name }}"
  register: build
  failed_when: "build.rc != 0"
  tags:
    - deploy


# Wait for build to complete
- name: "Wait up to {{ build_wait_time_seconds}} seconds for build {{ bc_name }} to complete"
  oc_obj:
    namespace: "{{ project_name }}"
    kind: "build"
    selector: "buildconfig={{ bc_name }}"
    state: list
    kubeconfig: "{{ lookup('env','HOME')}}/.kube/config"
  register: build
  until:
  - "{{'results' in build.results and build.results['results'] | count > 0}}"
  - "{{build.results.results[0] | json_query(jp_query) == 0 }}"
  delay: 15
  retries: "{{ (build_wait_time_seconds | int / 15) | int }}"
  vars:
    jp_query: "items[?status.phase!='Complete'&&status.phase!='Failed'] | length(@)"
  ignore_errors: yes
  tags:
    - deploy
