---
- name: Create CoolStore OpenShift project
  oc_project:
    display_name: "{{ project_display_name }}"
    name: "{{ project_name }}"
    state: present
    description: "{{ project_desc }}"
    kubeconfig: "{{ lookup('env','HOME')}}/.kube/config"
  tags:
    - deploy

- name: Give admin privileges to developer user
  oc_adm_policy_user:
    namespace: "{{ project_name }}"
    user: developer
    resource_kind: role
    resource_name: admin
    state: present
    kubeconfig: "{{ lookup('env','HOME')}}/.kube/config"
  tags:
    - deploy

- name: Give view privileges to default user
  shell: "oc adm policy add-role-to-user view -z default"
  register: cmd
  failed_when: "cmd.rc != 0"
  tags:
    - deploy        
