---
- hosts: localhost
  become: no
  vars_files:
  - ../vars.yml
  pre_tasks:
    - include: setup.yml
  roles:
    - { role: project, project_desc: "This project contains the front end and microservices for the CoolStore application.", project_display_name: "CoolStore Microservices" }
    - { role: nexus, when: nexus }
